<a href="https://colab.research.google.com/github/mohdnaved04/PYTHON/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("Numpy is installed")

x= np.array([1,2,3,4])
print("Array : " ,x)
print(type(x))

y= [1,2,3,4]
print("List : ", y)
print(type(y))

#Here you outputs will defferent for array [1 2 3 4] and  for list itll be [1,2,3,4]

Numpy is installed
Array :  [1 2 3 4]
<class 'numpy.ndarray'>
List :  [1, 2, 3, 4]
<class 'list'>


In [ ]:
%timeit [j**4 for j in range(1,5)]
# "%timeit" this funtion is used to show the time used for a loop to run


1.78 µs ± 434 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
import numpy as np
%timeit np.arange(1,5)**4
#arange create an array of evenly spaced values withinn speacific range

2.72 µs ± 773 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
#creating an array

import numpy as np
a= np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
#list to array

x= [1,2,3,4,5]
y= np.array(x)
y       #it'll run will show you the type of data it store
print(type(y))

<class 'numpy.ndarray'>


In [ ]:
#putting manual data in array

import numpy as np

l= []


for i in range(5):
  num= int(input("Enter no. to append: "))
  l.append(num)

print(l)

Enter no. to append: 1
Enter no. to append: 2
Enter no. to append: 3
Enter no. to append: 4
Enter no. to append: 5
[1, 2, 3, 4, 5]


In [ ]:
#Defining different dimensions of the array
import numpy as np

'''no of elements in 2d or 3d constituents
must be same otherwise there'll be an error'''

l=[1,2,3,4,5]
l2= [['a','ab'],['abc','abcd' ],['abcde','abcdef']]
l3= [[[1.2],[2.3],[3.4]], [[4.5],[5.6],[6.7]], [[7.8],[8.9],[9.0]]]
a=np.array(l)
a2=np.array(l2)
a3=np.array(l3)

a
print(a)
print(type(a))
print(a.ndim)

a2
print(a2)
print(type(a2))
print(a2.ndim)

a3
print(a3)
print(type(a3))
print(a3.ndim)




array([1, 2, 3, 4, 5])

In [ ]:
#explicitly telling the dimension of array

import numpy as np

a= np.array([2,3,4,5,6], ndmin=5)
print(a)
print(a.ndim)

[[[[[2 3 4 5 6]]]]]
5


In [ ]:
#creating a zero array

import numpy as np

a=np.zeros(4)
a2 = np.zeros((3,4))

print(a)
print(a2)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#creating a once array

import numpy as np

a= np.ones(4)
a2 = np.ones((3,4))
print(a)
print(a2)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#creating a empty array

a= np.empty(4)
print(a)

a2 = np.empty((2,3))
print(a2)

[1. 1. 1. 1.]
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [ ]:
#creating an array of range

import  numpy as np

a= np.arange(3)
print(a)

a2= np.arange(2,14)
print(a2)



[0 1 2]
[ 2  3  4  5  6  7  8  9 10 11 12 13]
2


In [ ]:
#creating an diagonal array

import numpy as np

a= np.eye(3)
print(a)

a2= np.eye(3,4)
print(a2)
print(a2.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
2


In [ ]:
#creating an array of linespace

import numpy as np

a= np.linspace(1,10,num=10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
#Using random funtion in numpy

import numpy as np

var= np.random.rand(4)
print(var)

var2= np.random.rand(2,5)
print(var2)

[0.78113698 0.32790419 0.80348915 0.93569149]
[[0.47821429 0.88890678 0.58102353 0.03545652 0.95663913]
 [0.00358516 0.64092004 0.3696007  0.92172622 0.94343369]]


In [ ]:
#usign randn : gives number close to zero maybe negative

import numpy as np

var= np.random.randn(4)
print(var)

var2= np.random.randn(2,5)
print(var2)

[ 0.41283386 -1.86577917 -0.54750319 -0.71188695]
[[-1.07303324 -0.35307892  0.40101647  0.0559062   0.84962455]
 [-0.0263885  -0.31072243  0.16170368 -0.13511802  0.28610442]]


In [ ]:
#usign ranf: gives one open and a close interval answer

import numpy as np

var= np.random.ranf(4)
print(var)

[0.27157516 0.89747481 0.97187062 0.79252332]


In [ ]:
#usign randint: give random number withing given range

import numpy as np

var= np.random.randint(1,10)
print(var)

var2= np.random.randint(1,10,5)
print(var2)

1
[9 6 8 4 9]


In [ ]:
#DATA TYPES

import numpy as np

x= np.array([1,2,3,4])
print(type(x))
print("Data type: ", x.dtype)

<class 'numpy.ndarray'>
Data type:  int64


In [ ]:
#DATA TYPES

import numpy as np

y= np.array([1.1,1.2,1.3,1.4])
print(type(y))
print("Data type: ", y.dtype)

<class 'numpy.ndarray'>
Data type:  float64


In [ ]:
#DATA TYPES

import numpy as np

y= np.array(['a','b','c','d'])
print(type(y))
print("Data type: ", y.dtype)

<class 'numpy.ndarray'>
Data type:  <U1


In [ ]:
#DATA TYPES

import numpy as np

y= np.array(["Akash","Amar", "Suraj"])
print(type(y))
print("Data type: ", y.dtype)

<class 'numpy.ndarray'>
Data type:  <U5


In [ ]:
#DATA TYPES

import numpy as np

y= np.array(["Akash","Amar", "Suraj",1,2,3,1.2,1,'a'])
print(type(y))
print("Data type: ", y.dtype)

<class 'numpy.ndarray'>
Data type:  <U32


In [ ]:
#DATA TYPES

import numpy as np

x= np.array([1,2,3,4], dtype= np.int8)
print(type(x))
print("Data type: ", x.dtype)

<class 'numpy.ndarray'>
Data type:  int8


In [ ]:
#changing data type

import numpy as np

x= np.array([1,2,3,4], dtype= "f")
print(type(x))
print("Data type: ", x.dtype)

<class 'numpy.ndarray'>
Data type:  float32


In [ ]:
#changing data type

import numpy as np


x= np.array([1,2,3,4])
new= np.float32(x)
new_one= np.int_(new)

print(type(new))
print(type(x))
print(type(new_one))

print("Data type: ", x.dtype)
print("Data type: ", new.dtype)
print("Data type: ", new_one.dtype)

print(x)
print(new)
print(new_one)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Data type:  int64
Data type:  float32
Data type:  int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:
import numpy as np


x= np.array([1,2,3,4])
new_1= x.astype(float)

print(x)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
''' There are several ways to convert a data type of a array such as
1.
x= np.array([1,2,3,4])
new_1= x.astype(float)

2.
x= np.array([1,2,3,4])
new= np.float32(x)
new_one= np.int_(new)


print("Data type: ", x.dtype)
print("Data type: ", new.dtype)
print("Data type: ", new_one.dtype)

3.
x= np.array([1,2,3,4], dtype= np.int8)


In [ ]:
#Arithmatic operations

import numpy as np

#ADDITION OF SCALER INTO ARRAY
var= np.array([1,2,3,4])

#var2= var +3
#var1= var-3
var1= np.subtract(var,3)
var2= np.add(var,3)

print(var1)
print(var2)


[-2 -1  0  1]
[4 5 6 7]


In [ ]:
#ADDITION/SUBTRACTION OF TWO MATRICESS

import numpy as np

x= np.array([1,2,3,4])
y= np.array([1,2,3,4])

#added= x+y
#subtract= x-y
added= np.add(x,y)
subtract= np.subtract(x,y)

print("Addition of matrices: ",added)
print("Subtraction of matrices: ",subtract)

Addition of matrices:  [2 4 6 8]
Subtraction of matrices:  [0 0 0 0]


In [ ]:
#Multiplicaton/Division of scaler with matrix

import numpy as np

var= np.array([1,2,3,4])
#var1= var*3
#var2= var/3
var1 = np.multiply(var,3)
var2= np.divide(var,3)
print(var1)
print(var2)


[ 3  6  9 12]
[0.33333333 0.66666667 1.         1.33333333]


In [ ]:
#using modulus in array

import numpy as np

var= np.array([1,2,3,4])
#var1= var%3
var1= np.mod(var,3)

print(var)
print(var1)

[1 2 3 4]
[1 2 0 1]


In [ ]:
#using power and reciprocal funtion in numpy
import numpy as np

var= np.array([1,2,3,4])

var1= var**2
var2= np.power(var,2)
var3= 1/var
var4= var.astype(float)
var5= np.reciprocal(var4)

print(var1)
print(var2)
print(var3)
print(var4)
print(var5)

[ 1  4  9 16]
[ 1  4  9 16]
[1.         0.5        0.33333333 0.25      ]
[1. 2. 3. 4.]
[1.         0.5        0.33333333 0.25      ]


In [ ]:
#using 2D arrays to do operations

import numpy as np

var21= np.array([[1,2,3,4,5], [5,6,7,8,9,]])
var22= np.array([[1,2,3,4,5], [5,6,7,8,9,]])

print( "Array one: ", var21)
print("Array two: ", var22)

added= var21+ var22
npadd= np.add(var21, var22)

print( "Added Arrays: \n", added, "\n", npadd)

Array one:  [[1 2 3 4 5]
 [5 6 7 8 9]]
Array two:  [[1 2 3 4 5]
 [5 6 7 8 9]]
Added Arrays: 
 [[ 2  4  6  8 10]
 [10 12 14 16 18]] 
 [[ 2  4  6  8 10]
 [10 12 14 16 18]]


In [ ]:
#BASIC ARITHMATIC FUNTIONS IN NUMPY

import numpy as np

var= np.array([1, 2, 3, 4, 5])

print("MIN: ", np.min(var), "\n", "MAX: ", np.max(var), "\nLOWEST ELEMENT POSITION: ", np.argmin(var), "\nSQUARING: " ,np.sqrt(var), "\nCUMULATIVE SUM: " ,np.cumsum(var), "\nSin values of var: ", np.sin(var),"\nCos values of var: ", np.cos(var), "\nlog values of var: ", np.log(var))



MIN:  1 
 MAX:  5 
LOWEST ELEMENT POSITION:  0 
SQUARING:  [1.         1.41421356 1.73205081 2.         2.23606798] 
CUMULATIVE SUM:  [ 1  3  6 10 15] 
Sin values of var:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] 
Cos values of var:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219] 
log values of var:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
#BASIC ARITHMATIC OPERATION IN PERFORMING IN 2D NUMPY ARRAY

import numpy as np

var= np.array([[1,2,3,4],[5,6,7,8]])
print("MIN: ", np.min(var), "\n", "MAX: ", np.max(var), "\nLOWEST ELEMENT POSITION: ", np.argmin(var), "\nSQUARE ROOT: \n" ,np.sqrt(var), "\nCUMULATIVE SUM: \n" ,np.cumsum(var), "\nSin values of var: \n", np.sin(var),"\nCos values of var: \n", np.cos(var), "\nlog values of var: \n", np.log(var))



MIN:  1 
 MAX:  8 
LOWEST ELEMENT POSITION:  0 
SQUARE ROOT: 
 [[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]] 
CUMULATIVE SUM: 
 [ 1  3  6 10 15 21 28 36] 
Sin values of var: 
 [[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825]] 
Cos values of var: 
 [[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003]] 
log values of var: 
 [[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]]


In [ ]:
#ARITHMATIC OPERATION ALONG AXIS

import numpy as np

var= np.array([[13,12,163,14],[55,60,17,18]])
print(" Along the column:" ,np.argmin(var, axis=0))
print( "Along the row: ", np.argmin(var, axis=1))


 Along the column: [0 0 1 0]
Along the row:  [1 2]


In [ ]:
# SHAPE AND RESHAPE OF AN NUMPY ARRAY

import numpy as np

var= np.array([[1,2],[1,2]])
var2= np.array([[1,2],[1,2],[1,2]])

print("var array: \n",var, "\n")
print("Shape of the var array: \n",var.shape, "\n")  #give the shape of the array provided.
print("var2 array: ",var2, "\n")
print("Shape of the var2 array: ",var2.shape)



var array: 
 [[1 2]
 [1 2]] 

Shape of the var array: 
 (2, 2) 

var2 array:  [[1 2]
 [1 2]
 [1 2]] 

Shape of the var2 array:  (3, 2)


In [ ]:
import numpy as np

var1= np.array([1,2,3,4], ndmin=2)

print("give the array:" ,var1)
print("give dimension of the array: ",var1.ndim)
print("give the shape of the array: ",var1.shape)



give the array: [[1 2 3 4]]
give dimension of the array:  2
give the shape of the array:  (1, 4)


In [ ]:
#RESHAPING OF THE ARRAY IN NUMPY

import numpy as np

var= np.array([1, 2, 3, 4, 5,6])
x= var.reshape(3,2)

print(var)
print(var.ndim)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
import numpy as np

var= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=var.reshape(2,3,2)

print(var)
print(var.ndim)

print(x)
print(x.ndim)

var2= x.reshape(12)
print(var2)

var3=x.reshape(-1)
print(var3)

var4= x.flatten()
print(var4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
import numpy as np

var= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=var.reshape(2,3,2)

print(x)

var3=x.reshape(-1)
print(var3)

x1= x.reshape(12)
print(x1)

var4= x.flatten()
print(var4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
import numpy as np

var1= np.array([1,2,3,4])
var2 = np.array([5,6,7,8])

print(var1+var2)

[ 6  8 10 12]


In [ ]:
import numpy as np

var1= np.array([1,2,3])
print(var1.shape)
print(var1)

print()

var2= np.array([[1],[2],[3]])
print(var2.shape)
print(var2)
print()

print(var1 + var2)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
import numpy as np

x= np.array([[1],[2]])
print(x.shape)
print()
y= np.array([[2,3,4],[5,6,7]])
print(y.shape)
print()

print(x+y)

(2, 1)

(2, 3)

[[3 4 5]
 [7 8 9]]


In [ ]:
import numpy as np

var= np.array([1,2,3])
print()
print(var)
print(var[0])
print(var[1])
print(var[2])
print()
print(var[-1])
print(var[-2])
print(var[-3 ])


[1 2 3]
1
2
3

3
2
1


In [ ]:
var= np.array([[1,2,3], [4,5,6]])

print(var)
print(var.ndim)
print(var.shape)
print()
print(var[0,2])
print(var[1,2])
print()

print(var[-1,-1])
print(var[-2,-1])

[[1 2 3]
 [4 5 6]]
2
(2, 3)

3
6

6
3


In [ ]:
var= np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(var)
print(var.ndim)
print(var.shape)
print()
print(var[0,1,2])
print(var[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)

6
12


In [ ]:
import numpy as np

var= np.array([1,2,3,4,5,6,7,8])
print(var.shape)

print(var[0:7:1])
print(var[0:7:2])
print()
print(var[1:6:2])
print(var[3:6:1])
print()
print(var[::])
print(var[::2])
print(var[::-2])
print()
print(var[-1:-6:-2])

x= np.array(var[0:7:2])
print(x)

(8,)
[1 2 3 4 5 6 7]
[1 3 5 7]

[2 4 6]
[4 5 6]

[1 2 3 4 5 6 7 8]
[1 3 5 7]
[8 6 4 2]

[8 6 4]
[1 3 5 7]


In [ ]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(x)
print()
print("from 9 to 12: ", x[2,3:0:-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

from 9 to 12:  [12 11 10]


In [ ]:
#interation in Numpy array

import numpy as np

arr= np.array([1,2,3,4])
print(arr)
print()

for i in arr:
  print(i, end=" ")

[1 2 3 4]

1 2 3 4 <class 'numpy.int64'>


In [ ]:
#iteration in 2-D array

import numpy as np

arr= np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
print()
print(np.ndim(arr))
print()


for i in arr:
  print(i)

print()
for m in arr:
  for j in m:
    print(j, end=" ")

[[1 2 3 4]
 [5 6 7 8]]

2

[1 2 3 4]
[5 6 7 8]

1 2 3 4 5 6 7 8 

In [ ]:
#iteration in 2-D array
#printing through inbuild numpy module package

import numpy as np

arr= np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
print()
print(np.ndim(arr))
print()

for n in np.nditer(arr, flags= ['buffered'], op_dtypes= ['S']):
  print(n, end=' ')


[[1 2 3 4]
 [5 6 7 8]]

2

b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' 

In [ ]:
#iteration in 2-D array
#printing through inbuild numpy module package

import numpy as np

arr= np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
print()
print(np.ndim(arr))
print()

for n in np.nditer(arr):
  print(n, end=' ')


[[1 2 3 4]
 [5 6 7 8]]

2

1 2 3 4 5 6 7 8 

In [ ]:
#iteration in 2-D array
#printing through inbuild numpy module package

import numpy as np

arr= np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
print()
print(np.ndim(arr))
print()

for n in np.ndenumerate(arr):
  print(n)


[[1 2 3 4]
 [5 6 7 8]]

2

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((1, 3), 8)


In [ ]:
#COPY VS VIEW IN NUMPY

import numpy as np

var= np.array([1,2,3,4])
co= np.copy(var)

print("array: ", var)
print("copied: ",co)

x= co.view()
print("view co: ", x)

y= var.view()
print("view var: ", y)


array:  [1 2 3 4]
copied:  [1 2 3 4]
view co:  [1 2 3 4]
view var:  [1 2 3 4]


In [ ]:
#JION ARRAY

import numpy as np

var1= np.array([1,2,3,4])
var2= np.array([9,8,7,6])
var3= np.array([10,11,12,13])

arr= np.concatenate((var1,var2, var3))
print(arr)


[ 1  2  3  4  9  8  7  6 10 11 12 13]


In [ ]:
#CONCAENATION ALONG THE AXIS

import numpy as np

var1= np.array([[1,2],[3,4]])
var2= np.array([[9,8],[7,6,]])
arr1= np.concatenate((var1, var2), axis=1)
arr2= np.concatenate((var1, var2), axis=0)

print("joinin through axis= 1 arr \n", arr1)
print("joinin through axis= o arr \n", arr2)


joinin through axis= 1 arr 
 [[1 2 9 8]
 [3 4 7 6]]
joinin through axis= o arr 
 [[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [ ]:
#USING STACK FUNTION IN NUMPY

import numpy as np

var1= np.array([1,2,3,4])
var2= np.array([9,8,7,6])

ar_new= np.stack((var1,var2), axis=1)
a_new= np.stack((var1, var2), axis=0)

print(ar_new)
print()
print(a_new)
print()

ar_h= np.hstack((var1,var2))  #work along the row
ar_v= np.vstack((var1,var2))  #work along the column
ar_d= np.dstack((var1,var2))  #work along the height

print(ar_h, "\n", ar_v, "\n", ar_d)

print( np.ndim(ar_h), "\n", np.ndim(ar_v), "\n", np.ndim(ar_d))


[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[[1 2 3 4]
 [9 8 7 6]]

[1 2 3 4 9 8 7 6] 
 [[1 2 3 4]
 [9 8 7 6]] 
 [[[1 9]
  [2 8]
  [3 7]
  [4 6]]]
1 
 2 
 3


In [ ]:
#SPILITING ARRAY

import numpy as np

var= np.array([1,2,3,4])
print(var)
print(var)

ar= np.array_split(var, 6)

print(ar)

[1 2 3 4]
[1 2 3 4]
[array([1]), array([2]), array([3]), array([4]), array([], dtype=int64), array([], dtype=int64)]


In [ ]:
#SPILITING ARRAY

import numpy as np

var= np.array([[1,2],[3,4],[5,6]])
print(var)
print()
ar= np.array_split(var,3)
ar0= np.array_split(var,3, axis=0)
ar1= np.array_split(var,2, axis=1)

print(ar)
print()
print(ar0)
print()
print(ar1)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [ ]:
#SEARCHING IN NUMPY ARRAY

import numpy as np

var= np.array([1,2,3,3,2,4,2,6])
#indexing      0,1,2,3,4,5,6,7

y= np.where(var%2==0)
print(y)

x= np.where(var==2)

print(x)

(array([1, 4, 5, 6, 7]),)
(array([1, 4, 6]),)


In [ ]:
#SEARCH SORT

import numpy as np

var= np.array([0,1,1,2,3,5,6,8,9,10,11,11])

x= np.searchsorted(var, 1)
print(x)
print()
y= np.where(var==11)
print(y)

z= np.searchsorted(var,1,side= "left")
k = np.searchsorted(var,1,side= "right")
print(z)
print()
print(k)

1

(array([10, 11]),)
1

3


In [ ]:
#PLACEMENT OF NUMBER IN SORTED ARRAY

import numpy as np

var= np.array([1,2,3,5,6,7,8,9,10])

x= np.searchsorted(var, [3,4,5,7])
print(x)    #itll print where given elements in the array should be inserted

[2 3 3 5]


In [ ]:
#USING SORT FUNTION IN NUMPY

import numpy as np

var= np.array([3,4,2,5,6,7,1,2])
print(np.sort(var))

[1 2 2 3 4 5 6 7]


In [ ]:
#USING SORT FUNTION IN NUMPY

import numpy as np

var= np.array(["b","a", "d"])
print(np.sort(var))

['a' 'b' 'd']


In [ ]:
import numpy as np

var= np.array([[1,2,0],[9,3,4],[8,5,6]])
print(np.sort(var))


[[0 1 2]
 [3 4 9]
 [5 6 8]]


In [ ]:
#USING FILTER IN NUMPY

var= np.array([ "a", "d", "c", "k"])

f= [True, False, True, False]
print(type(f))

new_a= var[f]
print(new_a)
print(type(new_a))

<class 'list'>
['a' 'c']
<class 'numpy.ndarray'>


In [ ]:
#USIGN SUFFLE FUNTION FROM RANDOM O

import numpy as np

var= np.array([1,2,3,4,5])

np.random.shuffle(var)
print(var)

[1 5 4 3 2]


In [ ]:
#USING UNIQUE FUNTION ON NUMPY

var= np.array([1,2,3,4,2,3,5,7])
x= np.unique(var, return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 7]), array([0, 1, 2, 3, 6, 7]), array([1, 2, 2, 1, 1, 1]))


In [ ]:
#USING RESIZE FUNTION OF NUMPY

import numpy as np

var= np.array([1,2,3,4,5,6])
x= np.resize(var, (2,3))
y= np.resize(var,(3,2))
z= np.resize(var, (2,2))

print(var, "\n", x, "\n", y , "\n", z)

[1 2 3 4 5 6] 
 [[1 2 3]
 [4 5 6]] 
 [[1 2]
 [3 4]
 [5 6]] 
 [[1 2]
 [3 4]]


In [ ]:
#USING FLATTEN FUNTION IN NUMPY

import numpy as np

var= np.array([1,2,3,4,5,6])
y= np.resize(var, (2,3))

print(y)
print()
print("FLATTEN F:",y.flatten(order="F"))
print("RAVEL A&K(same):",y.ravel(order="K"))


[[1 2 3]
 [4 5 6]]

FLATTEN F: [1 4 2 5 3 6]
RAVEL C&K(same): [1 2 3 4 5 6]


In [ ]:
#USING INSERT FUNTION IN NUMPY

import numpy as np

var= np.array([1,2,3,4,5])
v= np.insert(var, (2,4), 40)

print(var)
print(v)

[1 2 3 4 5]
[ 1  2 40  3  4 40  5]


In [ ]:
var= np.array([[1,2,3],[1,2,3]])

np.insert(var,2,[5,6],axis=1)

array([[1, 2, 5, 3],
       [1, 2, 6, 3]])

In [ ]:
#USING APPEND FUNTION OF NUMPY

import numpy as np
var= np.array([1,2,3])
x=np.append(var,[4,5,6], axis=0)
print(x)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
var= np.array([[1,2,3],[1,2,3]])
x=np.append(var,[[5],[6]], axis=1)
print(x)

[[1 2 3 5]
 [1 2 3 6]]


In [ ]:
#USING DELETE FUNTION ON NUMPY
#DELETE FUNTION WORK ON INDEXING

import numpy as np

var= np.array([1,2,3,4])
print(var)
print()
d= np.delete(var,2)
print(np.delete(var,2))
print()
print(d)



[1 2 3 4]

[1 2 4]

[1 2 4]


In [ ]:
#MATRIX

import numpy as np

mat= np.matrix([[1,2,3],[1,2,3]])
print(mat)

var= np.array([[1,2,3],[1,2,3]])
print(var)
print(type(mat))
print(type(var))
print()
print(mat.dtype)
print(var.dtype)

[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>
<class 'numpy.ndarray'>

int64
int64


In [ ]:
mat1= np.matrix([[1,2],[1,2]])
mat2= np.matrix([[1,2],[1,2]])
print(mat1 )
print()
print(mat2)
print()
print("NP sum:" ,np.add(mat1, mat2))
print()
print(np.subtract(mat1, mat2))
print()
print("multiply: " ,mat1*mat2)
print()
print(" dot product: ",mat1.dot(mat2))
print()
print("np multiply: ",np.multiply(mat1,mat2))
print()
print(" np divide: ",np.divide(mat1,mat2))
print()
print("divide: ",mat1/mat2)
print()



[[1 2]
 [1 2]]

[[1 2]
 [1 2]]

NP sum: [[2 4]
 [2 4]]

[[0 0]
 [0 0]]

multiply:  [[3 6]
 [3 6]]

 dot product:  [[3 6]
 [3 6]]

np multiply:  [[1 4]
 [1 4]]

 np divide:  [[1. 1.]
 [1. 1.]]

divide:  [[1. 1.]
 [1. 1.]]



In [ ]:
#TRANSPOSE MATRIX

import numpy as np

mat= np.matrix([[1,2,3],[4,5,6]])
print(mat)
print()
print(mat.T)
print()
print(np.transpose(mat))
print(np.swapaxes(mat,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
var= np.matrix([[1,2],[3,4]])
print(np.swapaxes(var,0,1))
print(var)

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


In [ ]:
var= np.matrix([[1,2],[3,4]])
print(var,'\n')

print(np.linalg.inv(var))
print()
print(np.linalg.det(var))
print()
print(np.linalg.matrix_rank(var))
print()
print("power:",np.linalg.matrix_power(var,2))
print()
print(np.linalg.eig(var))

values, vector= np.linalg.eig(var)
print(values)
print()
print(vector)


[[1 2]
 [3 4]] 

[[-2.   1. ]
 [ 1.5 -0.5]]

-2.0000000000000004

2

pwer: [[ 7 10]
 [15 22]]

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=matrix([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))
[-0.37228132  5.37228132]

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
